Attempt to fix the Docker Hub build error
Error:
The command '/bin/sh -c pip install -r /opt/sources/pip-req.txt' returned a non-zero code: 1

Root cause:
Downloading/unpacking psycopg2==2.5.3 (from -r /opt/sources/pip-req.txt (line 25))

  Running setup.py (path:/tmp/pip_build_root/psycopg2/setup.py) egg_info for package psycopg2

    Error: could not determine PostgreSQL version from '10.0'
    Complete output from command python setup.py egg_info:
    running egg_info

Suspected reason:
ENV variable for Postgres version is not set correctly